### ISSUE TITLE
unable to open new terminal after kube-up.sh

### ISSUE THREAD

**Issue by 4ndrej** [akranga/kube-workshop#2]
After running kube-up.sh it's unable to open new terminal on my fedora box, it's reporting

```
There was an error creating the child process for this terminal
getpt failed: No such file or directory
```

Only known cure is to reboot machine.
Seems to be same issue as https://github.com/kubernetes/kubernetes/issues/15577

**Comment by akranga** [comment]
change from 15577 seems to be okay... Successfully tested it on workshop in Kyiv
